shifting_cell_top:
	jg jg_fpv.tcl -allow_unsupported_OS -define SHIFTING_CELL_TOP 1&

shifting_row_top:
	jg jg_fpv.tcl -allow_unsupported_OS -define SHIFTING_ROW_TOP 1&

shifting_parallel_cell_top:
	jg jg_fpv.tcl -allow_unsupported_OS -define SHIFTING_PARALLEL_CELL_TOP 1&

shifting_parallel_row_top:
	jg jg_fpv.tcl -allow_unsupported_OS -define SHIFTING_PARALLEL_ROW_TOP 1&

data_shifter_top:
	jg jg_fpv.tcl -allow_unsupported_OS -define DATA_SHIFTER_TOP 1&

data_matrix_top:
	jg jg_fpv.tcl -allow_unsupported_OS -define DATA_MATRIX_TOP 1&

data_feeder_top:
	jg jg_fpv.tcl -allow_unsupported_OS -define DATA_FEEDER_TOP 1&